# 查询
GET http://localhost:3000/users/index HTTP/1.1



# POST http://localhost:3000/users/create HTTP/1.1
# Content-Type: application/json

# {
#     "name": "test",
#     "email": "1141395452@qq.com"
# }

